name: CI

on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: action/checkout@v5
      - name: runs a one-line script
        run: echo Hello World!
      - name: run a multiline script
        run: echo something idk
